<?php

/**
 * Implements hook_init().
 */
function nodejs_init() {
  register_shutdown_function(array('Nodejs', 'sendMessages'));
  $nodejs_config = nodejs_get_config();
  drupal_add_js(drupal_get_path('module', 'nodejs') . '/socket_io/support/socket.io-client/socket.io.js', array('type' => 'file'));
  drupal_add_js(drupal_get_path('module', 'nodejs') . '/nodejs.js', array('type' => 'file'));
  drupal_add_js(array('nodejs' => $nodejs_config), array('type' => 'setting'));
  foreach (nodejs_get_js_handlers() as $handler_file) {
    drupal_add_js($handler_file, array('type' => 'file'));
  }
}

/**
 * Get a list of javascript handler files.
 */
function nodejs_get_js_handlers() {
  $handlers = module_invoke_all('nodejs_handlers_info');
  drupal_alter('nodejs_js_handlers', $handlers);
  return $handlers;
}

/**
 * Implements hook_menu().
 */
function nodejs_menu() {
  return array(
    'nodejs/auth/%' => array(
      'title' => 'Who goes there?',
      'page callback' => 'nodejs_auth_check',
      'page arguments' => array(2),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'nodejs/stats' => array(
      'title' => 'Node.js server stats',
      'page callback' => 'nodejs_server_stats_page',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'nodejs/stats/users' => array(
      'title' => 'Node.js users stats',
      'page callback' => 'nodejs_users_stats_page',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'nodejs/stats/user/%user' => array(
      'title' => 'Node.js user stats',
      'page callback' => 'nodejs_user_stats_page',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'nodejs/stats/channel/%channel' => array(
      'title' => 'Node.js channel stats',
      'page callback' => 'nodejs_channel_stats_page',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Menu callback: renders overall users stats from the Node.js server.
 */
function nodejs_users_stats_page() {
  $page = array(
    '#type' => 'page',
    'content' => array(
      'nodejs' => array(
        '#markup' => __FUNCTION__,
      ),
    ),
  );
  return $page;
}

/**
 * Menu callback: renders stats for the given user from the Node.js server.
 */
function nodejs_user_stats_page($user) {
  $page = array(
    '#type' => 'page',
    'content' => array(
      'nodejs' => array(
        '#markup' => __FUNCTION__,
      ),
    ),
  );
  return $page;
}

/**
 * Menu callback: renders stats for the given channel from the Node.js server.
 */
function nodejs_channel_stats_page($channel) {
  $page = array(
    '#type' => 'page',
    'content' => array(
      'nodejs' => array(
        '#markup' => __FUNCTION__,
      ),
    ),
  );
  return $page;
}

/**
 * Menu callback: renders overall stats for the Node.js server.
 */
function nodejs_server_stats_page() {
  $page = array(
    '#type' => 'page',
    'content' => array(
      'nodejs' => array(
        '#markup' => __FUNCTION__,
      ),
    ),
  );
  return $page;
}

/**
 * Override or insert variables into the page template.
 */
function nodejs_preprocess_page(&$variables) {
  if (variable_get('nodejs_debug', FALSE)) {
    $variables['page']['content']['nodejs_debug'] = array('#markup' => '<div id="nodejs-debug-wrapper"><h3>Node js debug</h3></div>');
  }
}

/**
 * Menu callback: checks the given key to see if it matches a valid session.
 */
function nodejs_auth_check($auth_key) {
  $uid = db_query("SELECT uid FROM {sessions} WHERE sid = :sid", array(':sid' => $auth_key))->fetchField();
  $auth_user = $uid > 0 ? user_load($uid) : drupal_anonymous_user();
  $auth_user->nodejs_valid_auth_key = $uid !== FALSE;
  $auth_user->channels = (variable_get('nodejs_enable_userchannel', TRUE)) ? array('user_' . $user->uid) : array();
  foreach (module_invoke_all('nodejs_channels_info') as $channel) {
    $auth_user->channels[] = $channel;
  }

  drupal_json_output($auth_user);
  drupal_exit();
}

/**
 * Get nodejs server config.
 */
function nodejs_get_config() {
  global $user;

  static $nodejs_config;

  $channels = (variable_get('nodejs_enable_userchannel', TRUE)) ? array('user_' . $user->uid) : array();
  foreach (module_invoke_all('nodejs_channels_info') as $channel) {
    $channels[] = $channel;
  }
  drupal_alter('nodejs_js_channels', $channels);

  if ($nodejs_config === NULL) {
    $defaults = array(
      'host' => 'localhost',
      'port' => 8080,
      'resource' => '/node.js/realtime',
      'authkey' => session_id(),
      'uid' => $user->uid,
      'channels' => $channels,
    );
    $nodejs_config = variable_get('nodejs_config', array()) + $defaults;
  }
  return $nodejs_config;
}

class Nodejs {

  public static $messages = array();

  public static function getMessages() {
    return self::$messages;
  }

  public static function enqueueMessage(StdClass $message) {
    self::$messages[] = $message;
  }

  public static function sendMessages() {
    $config = nodejs_get_config();
    foreach (self::$messages as &$message) {
      $message->authkey = session_id();
      drupal_http_request('http://' . $config['host'] . ':' . $config['port'] . '/publish', array('method' => 'POST', 'data' => drupal_json_encode($message)));
    }
  }
}

