<?php

/**
 * Implements hook_init().
 */
function nodejs_notify_init() {
  drupal_add_library('system', 'ui.dialog');
  drupal_add_css(drupal_get_path('module', 'nodejs_notify') . '/libraries/jgrowl/jquery.jgrowl.css');
  drupal_add_js(drupal_get_path('module', 'nodejs_notify') . '/libraries/jgrowl/jquery.jgrowl.js');
}

/**
 * Implements hook_nodejs_handlers_info().
 */
function nodejs_notify_nodejs_handlers_info() {
  return array(
    drupal_get_path('module', 'nodejs_notify') . '/nodejs.notify.js',
  );
}
