<?php

/**
 * Implements hook_nodejs_handlers_info().
 */
function nodejs_notify_nodejs_handlers_info() {
  return array(
    drupal_get_path('module', 'nodejs_notify') . '/nodejs.notify.js',
  );
}

/**
 * Implements hook_action_info().
 */
function nodejs_notify_action_info() {
  $actions = array();

  $triggers = module_invoke_all('trigger_info');
  drupal_alter('trigger_info', $triggers);

  foreach (array('node', 'user', 'comment', 'system') as $type) {
    $actions['nodejs_notify_' . $type . '_action'] = array(
      'type' => $type,
      'triggers' => array_keys($triggers[$type]),
      'label' => t("Publish realtime notifications of $type activity."),
      'configurable' => FALSE,
    );
  }
  return $actions;
}

/**
 * Node object action callback.
 *
 * @param object $node
 * @param array $context
 */
function nodejs_notify_node_action($node, $context = array()) {

}

/**
 * Comment object action callback.
 *
 * @param object $node
 * @param array $context
 */
function nodejs_notify_comment_action($comment, $context = array()) {

}

/**
 * User object action callback.
 *
 * @param object $node
 * @param array $context
 */
function nodejs_notify_user_action($user, $context = array()) {
  $message = (object) array(
    'broadcast' => TRUE,
    'data' => (object) array(
      'subject' => t('System event.'),
      'body' => print_r(array($system, $context), TRUE),
    ),
    'channel' => 'nodejs_notify',
  );
  nodejs_enqueue_message($message);
}

/**
 * System object action callback.
 *
 * @param object $node
 * @param array $context
 */
function nodejs_notify_system_action($system, $context = array()) {
  $message = (object) array(
    'broadcast' => TRUE,
    'data' => (object) array(
      'subject' => t('System event.'),
      'body' => print_r(array($system, $context), TRUE),
    ),
    'channel' => 'nodejs_notify',
  );
  nodejs_enqueue_message($message);
}

/**
 * Implements hook_init().
 */
function nodejs_notify_init() {
  drupal_add_library('system', 'ui.dialog');
  drupal_add_css(drupal_get_path('module', 'nodejs_notify') .'/libraries/jgrowl/jquery.jgrowl.css');
  drupal_add_js(drupal_get_path('module', 'nodejs_notify') .'/libraries/jgrowl/jquery.jgrowl.js');
}

